/* Creating an enum of all the Stripe events. */
export enum StripeEvents {
    cutomerUpdated = 'customer.updated',
    customerDeleted = 'customer.deleted',
    customerSubscriptionCreated = 'customer.subscription.created',
    customerSubscriptionUpdated = 'customer.subscription.updated',
    customerSubscriptionDeleted = 'customer.subscription.deleted',
    customerSubscriptionTrialWillEnd = 'customer.subscription.trial_will_end',
    chargeCaptured = 'charge.captured',
    chargeFailed = 'charge.failed',
    chargeRefunded = 'charge.refunded',
    chargeSucceded = 'charge.succeded',
    chargeDisputeCreated = 'charge.dispute.created',
    chargeDisputeClosed = 'charge.dispute.closed',
    chargeDisputeFundsWithdrawn = 'charge.dispute.funds_withdrawn',
    chargeDisputeFundsReinstated = 'charge.dispute.funds_reinstated',
    invoicePaymentFailed = 'invoice.payment_failed',
    invoicePaymentSucceeded = 'invoice.payment_succeeded',
    invoiceUpdated = 'invoice.updated',
    invoiceFinalized = 'invoice.finalized',
    invoicePaid = 'invoice.paid',
    payoutCreated = 'payout.created',
    payoutFailed = 'payout.failed',
    payoutPaid = 'payout.paid',
    payoutCanceled = 'payout.canceled',
    radarEarlyFraudWarningCreated = 'radar.early_fraud_warning.created',
    radarEarlyFraudWarningUpdated = 'radar.early_fraud_warning.updated',
    transferCreated = 'transfer.created',
    transferFailed = 'transfer.failed',
    transferPaid = 'transfer.paid',
    transferReversed = 'transfer.reversed',
    transferUpdated = 'transfer.updated',
    paymentIntentSucceeded = 'payment_intent.succeeded',
    paymentIntentCreated = 'payment_intent.created',
    paymentIntentFailed = 'payment_intent.failed',
  }
  